[
  {
    title: "Learn Redux Toolkit",
    description: "Complete Redux Toolkit beginner tutorial",
    status: "pending",
    priority: "high",
    assignedTo: "Ravi",
  },
  {
    title: "Ravi Kumar",
    description: "Create profile details",
    status: "in-progress",
    priority: "medium",
    assignedTo: "Admin",
  },
  {
    title: "Complete API Integration",
    description: "Integrate frontend with backend APIs",
    status: "pending",
    priority: "high",
    assignedTo: "Meena",
  },
  {
    title: "Write Unit Tests",
    description: "Add Jest tests for all modules",
    status: "pending",
    priority: "medium",
    assignedTo: "Arjun",
  },
  {
    title: "Deploy Backend Server",
    description: "Deploy Node API to production",
    status: "pending",
    priority: "high",
    assignedTo: "Ravi",
  },
  {
    title: "Fix Authentication Bug",
    description: "Resolve incorrect token validation issue",
    status: "in-progress",
    priority: "high",
    assignedTo: "Karan",
  },
  {
    title: "Create Dashboard UI",
    description: "Design and build dashboard layout",
    status: "pending",
    priority: "medium",
    assignedTo: "Priya",
  },
  {
    title: "Optimize Database Queries",
    description: "Improve performance of heavy queries",
    status: "in-progress",
    priority: "high",
    assignedTo: "Sita",
  },
  {
    title: "Learn Docker Basics",
    description: "Complete Docker fundamentals course",
    status: "pending",
    priority: "low",
    assignedTo: "Ravi",
  },
  {
    title: "Prepare Project Documentation",
    description: "Write README and API docs",
    status: "pending",
    priority: "medium",
    assignedTo: "Meena",
  },
  {
    title: "Implement JWT Middleware",
    description: "Add JWT auth middleware to routes",
    status: "completed",
    priority: "high",
    assignedTo: "Arjun",
  },
  {
    title: "Add Dark Mode Feature",
    description: "Implement theme switching option",
    status: "pending",
    priority: "low",
    assignedTo: "Priya",
  },
  {
    title: "Review Pull Requests",
    description: "Check and approve pending PRs",
    status: "in-progress",
    priority: "medium",
    assignedTo: "Karan",
  },
  {
    title: "Refactor User Module",
    description: "Clean and reorganize user-related code",
    status: "pending",
    priority: "medium",
    assignedTo: "Sita",
  },
  {
    title: "Implement Search Functionality",
    description: "Add search API and frontend UI",
    status: "pending",
    priority: "high",
    assignedTo: "Ravi",
  },
  {
    title: "Add Pagination Support",
    description: "Implement backend + UI pagination",
    status: "completed",
    priority: "low",
    assignedTo: "Arjun",
  },
  {
    title: "Set Up CI/CD Pipeline",
    description: "Configure GitHub Actions",
    status: "in-progress",
    priority: "high",
    assignedTo: "Meena",
  },
  {
    title: "Integrate Payment Gateway",
    description: "Add Razorpay integration",
    status: "pending",
    priority: "high",
    assignedTo: "Karan",
  },
  {
    title: "Improve Error Handling",
    description: "Add global error middleware",
    status: "pending",
    priority: "medium",
    assignedTo: "Priya",
  },
  {
    title: "Write API Usage Guide",
    description: "Prepare API reference guide",
    status: "pending",
    priority: "low",
    assignedTo: "Sita",
  },
];
